"""Update models

Revision ID: 2d0d062ad411
Revises: d279d9026825
Create Date: 2024-10-16 19:58:39.712820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0d062ad411'
down_revision: Union[str, None] = 'd279d9026825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_publisher_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'publisher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_publisher_id_fkey', 'books', 'publishers', ['publisher_id'], ['id'])
    # ### end Alembic commands ###
