"""Update models

Revision ID: a325926514e0
Revises: 2d0d062ad411
Create Date: 2024-10-16 20:03:02.308712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a325926514e0"
down_revision: Union[str, None] = "2d0d062ad411"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("publisher_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "books", "publishers", ["publisher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "publisher_id")
    # ### end Alembic commands ###
